### ISSUE TITLE
Credential management store does not work on https localhost

### ISSUE THREAD

**Issue by MichaelScript** [GoogleChromeLabs/credential-management-sample#12]
Cross posting from: https://gist.github.com/MichaelScript/1ea27fe211fe55f278108816f0c8754a#file-credential-api-not-working-on-https-localhost

* Running the following code on https://google.com returns expected behavior, Chrome prompts you to save your credentials

* This also works if you spin up an http server
i.e: `python -m SimpleHTTPServer` and run it in your console.

* However running on https://localhost results in a silent failure where the success function fires but you are not prompted.
Easy way to spin up a simple https server is: https://gist.github.com/dergachev/7028596
```
var creds = new PasswordCredential({
	id: "test@test.com",
	password:"password1"
});

navigator.credentials.store(creds).then(function(){
	console.log("Done saving credentials");
});
```

**Comment by agektmr** [comment]
To use Credential Management API on localhost you don't need HTTPS.

**Comment by MichaelScript** [comment]
Found out it's just inconsistency between TLS only APIs:
https://bugs.chromium.org/p/chromium/issues/detail?id=806642
